version: "2"
run:
  modules-download-mode: vendor

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: package-comments  # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
